language: node_js
node_js:
- 6.9.4
before_script: chmod 0777 ./node_modules/mocha/bin/mocha
before_install:
- openssl aes-256-cbc -K $encrypted_6a3d15ed6de0_key -iv $encrypted_6a3d15ed6de0_iv -in QuickRent.pem.enc -out QuickRent.pem -d
after_success:
- chmod 700 ./quickrent.pem
- ssh -i ./quickrent.pem -o "StrictHostKeyChecking no" ubuntu@ec2-107-22-117-119.compute-1.amazonaws.com "cd apps/QuickRent && sudo git pull"
- ssh -i ./quickrent.pem -o "StrictHostKeyChecking no" ubuntu@ec2-107-22-117-119.compute-1.amazonaws.com "cd apps/QuickRent/database forever start mlab_connection.js"