language: node_js
node_js:
- 6.9.4
before_script: chmod 0777 ./node_modules/mocha/bin/mocha
before_install:
- openssl aes-256-cbc -K $encrypted_6a3d15ed6de0_key -iv $encrypted_6a3d15ed6de0_iv -in quickrent.pem.enc -out quickrent.pem -d
after_success:
- chmod 400 ./quickrent.pem
- ssh -i ./quickrent.pem ubuntu@ec2-52-32-216-134.us-west-2.compute.amazonaws.com "cd apps/Quickrent"
- ssh -i ./quickrent.pem ubuntu@ec2-52-32-216-134.us-west-2.compute.amazonaws.com "git pull"

