language: node_js
node_js:
- 6.9.4
before_script: chmod 0777 ./node_modules/mocha/bin/mocha
deploy:
  skip_cleanup: true
  wait-until-deployed: true
  access_key_id: AKIAJGJAP6S7ROFUKAUA
  secret_access_key: 
  region: us-west-2
  provider: codedeploy  
  application: QuickRent
  deployment_group: QuickRent
