language: node_js
node_js:
- 6.9.4
before_script: chmod 0777 ./node_modules/mocha/bin/mocha
deploy:
  skip_cleanup: true
  wait-until-deployed: true
  region: us-west-2
  provider: codedeploy
  access_key_id: AKIAJGJAP6S7ROFUKAUA
  application: QuickRent
  deployment_group: QuickRent
env:
  global:
    secure: Oz26zP/j1TzGtIx0RJ+t3bRZSnhZ32QTLTyLh+U0LPmBfG2mamaXmXoeCgzlOv/Y1IebXKxV1Pr2J+gkeWqVRFypEs+F3L3nvYtx66HVNM33XyXe6BYai6ti9VnWrJK5M0bMSEnc6KNUzCYtMnB4lOlUhzSmWoksppG+gTv92zrtfvUwrSIEZtk/bnJntLVBR1ZCQG9EjIqwVNIja9srpyevKEbnTYnR5KwnJjkrIpmY35Nz0DOmmCevK3DLYwy+a+sl3Bk+iZRuOI+ADFAcDq3EaPbam8j3KMHBbSZYdU6gYGoBXvfLgEh9RUDIz+mS9xRixo7DjImYPZyq1+s2VX1HPkymbflELWpE5WyCgY3aLDLhJpU7QM13V/Ed4SSXxyV4b2p8nWW0U07XkfeApgYTxUa4xj2xmjBPLwvD5kNrVqRBK7d+SiKeh323rjYnNXT02JFM47ynIQo9x8fwUm+uqgyIDNVR8ZIdvJhvyRcK75o/DtM/euNVh5OyLJSTF/6FW5KGuBq93h2A1Ih/9HkVA94Tr01d9bMmu4J/ZjGoxt/MKzjfyF2jUqErLoEMVD0Wn4rkJ6b22ZjG/qU3T9PYF948A+uqMLoOlXvNXpwSsLc1j8ohsrOZk5T1HntHGEiksNrQOImJprbK20UssgDW8gnNo34LL24mAjrQUlM=
