language: node_js
node_js:
- 6.9.4
before_script: chmod 0777 ./node_modules/mocha/bin/mocha
deploy:
  skip_cleanup: true
  wait-until-deployed: true
  access_key_id: AKIAJGJAP6S7ROFUKAUA
  secret_access_key:
    secure: "Z7056SRZqx3s6RlAzqAgDjxDQaNYNFGpOGl8Jk1hgcX7BU7YnMC0rv8pLLXWJRehffp3R1xAXuxDr0Nd1R6FDOy8wQtidMhNYSLI5wWSZ5PcpcJB/ygfBvvw7O1AWT4jRk1EwsuFORsYisRJv8EX9LgYKdGQmR4yIfpo/IEgBen9D8QMAgPNnjc/L52YIi6TtMBK+zsx+pU/sFtdUyO9CeZh0k1EMaeNdckupV7dFTt7yPR4gzlah8xDeZsWIpDKFg2ZYGgrA/AKHnoTsd7MmhBzS5GhAfiKYN6oXq6Jp/dEgY4hMlUEcB6C4Pwhf7pCJAp/kHooFPNB182jtzfSozb0qH4MH4AvSU+z85HLcWRALIcntRv0Xil0pySG1h8gYVua4O427DnyrDXAdAVDtdsvugfBscFP9rwCtuJmH8sqC5DgpeGHmeDGLasw9q44SBw5t+T34/CeGoDQa2aSywsz4GmujC3IZ38oIdqAIAzC17kCi8Nrkl0YmrUVVQhUPB1kVvnEv1dtHfcBMRUaXtCFE3Z/XBEpBK+5mSuuPtvnghEw/Dpn37tE+vwGsJWHab5qzjiGqGaKC8awPkMAWswUietmcS0OPxfE/9KQB3RTWJy9eV+FwzTwft7mXvzVoGnl3VroAXGcmpvA4axZQlhNF/ZO49Q+gp4DlPAusvk="        
  region: us-west-2
  provider: codedeploy  
  application: QuickRent
  deployment_group: QuickRent
