language: node_js
node_js:
- 6.9.4
before_script: chmod 0777 ./node_modules/mocha/bin/mocha
deploy:
  skip_cleanup: true
  wait-until-deployed: true
  region: us-west-2
  provider: codedeploy
  access_key_id: AKIAJGJAP6S7ROFUKAUA
  secret_access_key:&1
        secure: "OenCInL4WBYU/15p6c5cVSNboTZ67+p/+hwHywx3L8lTurGE8VcSKpCWwD2sEsOT4YGDGLloB6hj05ETZxVG72ZOQ4D9e/zgQASAvpVv06fjCG9b3fE2WeYXrIv2dU5LHdHW4W5ly7JTVk2sRvA+wfchTjIhh1mP7nNMuQcuxxYya6fDq2A3m++n4QltHf+YWzzcepsDsKFKqtlLP1wrUvriKf4o5iGd07bPMf8oaoYQRSMhi3vlYqGnwdvYaEHJMxSdPLOhYXzHpt4MAXObIYsepjER0FvgRLge5EJc31nEPocN3gfGSF4+BYZp9ZjhAdZ2jqp0XDzbSRbY+aU52ux1RcjV0066dH1hxiDtjXijtXWX1NsFNCjmXmqtl4mxvGizpw7Ve96izQp4HSKSAMx6R0BQsINhlwvOcclFUGHo5fLUzS6+umth+DzkXoB5E2TOMrONoKlDYD77bej8gqukOEMINBLFMouTFiS9MoxAu2o+yrX5kpYqWx48s4G38JeZrcKTp59qltJ/mYuWldJxVXvLsaWsp3VAUiEzIiQ229e49p5Tw6Ck6AawrADFnvoZkQmHDBurIU/h/yeqoEGKvjoIF0Q3z4GBMDO6OCZT7CNjoIiKLIIVIVKdc39iW8qYjHZigb+pMd0rVoLzEPgCuCsecZah+tegEKeSawk="
  application: QuickRent
  deployment_group: QuickRent
